### ISSUE TITLE
transparent_spectra_plotting version 2

### ISSUE THREAD

**Issue by JayYu113** [vanessa-king/UBC_LAIR#101]
functions/visualization/transparent_spectra_plotting.m: to optimize a grid mask plot: plot all dIdV spectra on a selected mask(or manually select some) with some transprancy, and plot the average dIdV, which has a thicker linewidth.

**Comment by m-altthaler** [comment]
I wrote the function. I'll let Jiabin test it on his data. It's largely based on James' function it just accepts a mask now as optional input and used find to extract all xy coords of masked points then loops those to plot the corresponding I(V) or dIdV(V) (it does accept I(V) data but there is no layout case for that yet... (the option so set a layout case is there)

**Comment by m-altthaler** [comment]
-> transparentLinePlot.m
