### ISSUE TITLE
Average forward and backward bias sweeps - remove from load block, make into its own block

### ISSUE THREAD

**Issue by vanessa-king** [vanessa-king/UBC_LAIR#130]
Specifically for the Matrix load function, but double check that its consistent with the Nanonis load function

**Comment by jsk2355** [comment]
Is this about gridLoadDataUpward function? If so, what this function does when the average_forward_and_backward is selected is to separate I_forward and I_backward from I_all. Unlike Nanonis loading function, if this is not selected, I_all from the grid is all I (forward and backward together). If I understood correctly, I'll modify this function to match the way Nanonis loading.

**Comment by vanessa-king** [comment]
This issue is redundant. The separated forward and backward from Nanonis style data can already be averaged. Once we make the standardized load function for Matrix style data, then we don't need this
