### ISSUE TITLE
Typo in gridMaskLineSegmment? 

### ISSUE THREAD

**Issue by Plswearpants** [vanessa-king/UBC_LAIR#134]
the function gridMaskLineSegment used a function called createLineMask(line 221) to create a mask, but there is no createLineMask function in the Main branch; only createLineSegmentMask exists. Is this a typo in the code?

**Comment by m-altthaler** [comment]
It is a typo. We changed the name of the helper function  as the function actually makes a line segments (between to points) not the lien extending to the edge. I'll fix both issues and also move the helper functions to the right folder.
