### ISSUE TITLE
Altered x,y in function createLineSegmentMask

### ISSUE THREAD

**Issue by Plswearpants** [vanessa-king/UBC_LAIR#135]
For function "createLineSegmentMask," line 54:
mask(y1, x1) = 1
Why did you alter the x and y in the mask? Is it to make it aligned with the data? Or is it a typo?

**Comment by m-altthaler** [comment]
I looked into it and I think you're describing an outdated version of the function. (It uses Bresenham's line algorithm) but that is not the latest version I made. 
I'll update to the new version
