### ISSUE TITLE
VS02A: clicking doesn't work

### ISSUE THREAD

**Issue by jsk2355** [vanessa-king/UBC_LAIR#171]
When I run this block, it doesn't give me a chance to click the image to choose any point on the image. It just proceed to ask me to save the image. I think it's giput problem.

**Comment by rysagree** [comment]
Also a typo in line 85: 'lenght' should be length

**Comment by rysagree** [comment]
Problem found: offset and n are flipped in the function call in the block. Flip them and it works.

**Comment by rysagree** [comment]
Fixed, tested and merged
