### ISSUE TITLE
wishlist items

### ISSUE THREAD

**Issue by jamesday76** [vanessa-king/UBC_LAIR#69]
These are things we want but don't need.

- click to define line across gridmap to generate a waterfall plot of spectra
- subtract one gridmap from another (did Tiffany make one?)
- plotting spectra at multiple temperatures
- plotting all spectra with mean and standard deviation curves
- extract image locations and stitch them together to form a larger image file

**Comment by vanessa-king** [comment]
I would advocate for all these items to be registered as separate issues, then all given the 'enhancement' label. That way we can keep conversations/progress recorded for each one individually
