### ISSUE TITLE
gridClickForSpectrum grid variable issue

### ISSUE THREAD

**Issue by vanessa-king** [vanessa-king/UBC_LAIR#71]
The last input variable of gridClickForSpectrum, grid, is supposed to be optional. But there is an error when you don't provide grid. As a result, it always displays topo instead of a grid slice, as per lines 46-57:

`% use cases for different function arguments -> use dIdV at imageV, or use the topo
switch nargin
    case 8 % grid data is provided, use the topology instead
        z_img = topoPlaneSub(grid,200,0); % subtract plane
        fig_name = 'Topology associated with grid';

        fig_plot = imresize(z_img, [size(didv,2), size(didv,3)]);
    case 7 % grid data not provided, use the didv slice at imageV
        fig_name = ['Image of states at ',num2str(imageV),' V'];
        [~,imN] = min(abs(V_reduced-imageV));
        fig_plot = squeeze(didv(imN,:,:));
end`

**Comment by m-altthaler** [comment]
grid = [] in arguments block makes the input optional 
switch nargin case8/case7 -> if isepty(grid) 
fixed on MA_dev_masked_plots branch for testing
