### ISSUE TITLE
spectra with means and std devs

### ISSUE THREAD

**Issue by jamesday76** [vanessa-king/UBC_LAIR#76]
We could create a block that plots all spectra with mean and standard deviation curves.

**Comment by m-altthaler** [comment]
I'll make this a function that takes data(x,y,V) and a mask(x,y). 
It will likely plot all data using the transparent form and the average/mean on top. As well as upper/lower envelopes for STD

**Comment by m-altthaler** [comment]
-> transparentMeanSTDplot.m
