### ISSUE TITLE
waterfall plots

### ISSUE THREAD

**Issue by jamesday76** [vanessa-king/UBC_LAIR#78]
Click to define a line across a grid map, to generate a waterfall plot of spectra.

**Comment by m-altthaler** [comment]
we have a function that creates a line (segment) mask already.
What we need is a function that takes data(x,y,V), V, mask(x,y) and plots the waterfall plot for all data vs V as indicated by the mask

**Comment by m-altthaler** [comment]
-> waterfallLinePlots.m
