### ISSUE TITLE
load sxm function nanonis 

### ISSUE THREAD

**Issue by Plswearpants** [vanessa-king/UBC_LAIR#81]
Nanonis has a default function to load sxm, make is to be aligned with our code.

**Comment by vanessa-king** [comment]
Dong has made loadSXM.m, and then I will write a wrapper script that transforms the output from it into the matrix-style data we are used to

**Comment by vanessa-king** [comment]
* Note: compared to the original orientation of the data, loadsxm, then imshow(data) has the data flipped horizontally

**Comment by vanessa-king** [comment]
Note: make it so that the load functions DO NOT define the data struct, but instead return each individual piece of information

**Comment by vanessa-king** [comment]
Created load_topo_Nanonis.m as a wrapper function to load_sxm.m
