### ISSUE TITLE
Add a cropData function

### ISSUE THREAD

**Issue by vanessa-king** [vanessa-king/UBC_LAIR#90]
Add a cropData function.
Based off of Dong's current cropData function in his QPI scripts - or more similar to how our other masking functions work? 
What is more useful in general?

**Comment by m-altthaler** [comment]
Should be restricted to crop a n x m grid to n' x m', where n' and m' are a subset of the original coordinate axis.

**Comment by Plswearpants** [comment]
gridCropMask addresses the problem.
